name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org/"
      - name: Install dependencies
        run: npm install
      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build package to upload to GitHub releases
        run: |
          npm pack
          mv rate-limit-redis-*.tgz rate-limit-redis.tgz
      - name: Create a Github release
        uses: softprops/action-gh-release@v1
        with:
          files: rate-limit-redis.tgz
          body: You can view the changelog
            [here](https://github.com/wyattjoh/rate-limit-redis/blob/main/changelog.md).
